### ISSUE TITLE
Trying out the clojure parquet example - `(pwriter/test-schema)` Missing symbol

### ISSUE THREAD

**Issue by shlomi-dr** [gerritjvv/fileape#20]
Looking at the source, no such symbol exists.. 

What should the example be for this to work?

**Comment by gerritjvv** [comment]
Hi, I didn't see this ticket till now. 
This was a documentation error from my side. The test-schema refers to a schema that you've created.
Remember for parquet messages you need to define a schema for the parquet file. 
There is a `parse-schema` helper function that allows you to pass in the schema as text and use it in the code.

I've updated the documentation and add the same example below.

```(def schema (pwriter/parse-schema "message test{ required binary name; int32 id;}"))

(def ape2 (ape/ape {:codec :parquet :base-dir "/tmp/testdir" :parquet-codec "gzip" :message-type schema}))

;;for each key we must register a parquet schema and codec
;; the fileape.parquet.writer namespace has helper functions for compiling parquet definition schemas

(ape/update-env! ape2 "a" :parquet-codec :gzip :message-type schema)


;;; note that the callback function sets a :parquet key
;;; this contains the open parquet file context
(ape/write ape2 "a" (fn [{:keys [parquet]}] 
			(pwriter/write! parquet
			  {"name" "abc" "id" 1})))
```

**Comment by gerritjvv** [comment]
closing the issue for now unless you find another issue in the example, feel free to open another ticket.

**Comment by shlomi-dr** [comment]
Thank you for the detailed response! I will give it a try 😅
