### ISSUE TITLE
Missing dependency on clj-tuple

### ISSUE THREAD

**Issue by blalor** [gerritjvv/fileape#9]
There's a reference to `clj-tuple` in io.clj, but the dependency isn't declared in fileape's `project.clj`.  `tuple` has kind of come and gone and sort of come back in clj-tuple, and it's currently just `(def tuple vector)`.  

I've tried adding an explicit dependency to clj-tuple in my project, but I still get an error about tuple not existing (0.2.2) or ClassNotFoundException: clojure.lang.PersistentUnrolledVector (0.1.7), so there's something also going on with clj-tuple that I don't understand.

**Comment by gerritjvv** [comment]
hi, I'll try and have a look, maybe remove tuple completely from this and make a new release.

**Comment by gerritjvv** [comment]
try it out with the latest 0.8.5 release. I've remove clj-tuple completely and also upgraded to the latest stable core.async lib.

**Comment by gerritjvv** [comment]
closing this issue for now, please reopen if the bug persists.
